version: "3.4"

services:
  samba:
    image: dperson/samba
    environment:
      TZ: "Europe/Sofia"
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /downloads:/downloads:z
      - /downloads2:/downloads2:z
    command: '-s "Mount;/downloads" -s "Bobs Volume;/downloads2;yes;no;no;bob" -u "bob;bobspasswd" -p'

networks:
  default:
